
// SPDX-License-Identifier: GPL-3.0-only
/*
 * Copyright (c) 2023 Dengfeng Liu <liudf0716@gmail.com>
 */

#ifndef _WDCTL_H_
#define _WDCTL_H_

#define DEFAULT_SOCK	"/tmp/wdctl.sock"

#define WDCTL_UNDEF		0
#define WDCTL_STATUS	1
#define WDCTL_STOP		2
#define WDCTL_KILL		3
#define WDCTL_RESTART	4
#define WDCTL_ADD_TRUSTED_DOMAINS		5
#define	WDCTL_REPARSE_TRUSTED_DOMAINS	6
#define	WDCTL_CLEAR_TRUSTED_DOMAINS		7
#define	WDCTL_SHOW_TRUSTED_DOMAINS		8
#define	WDCTL_ADD_DOMAIN_IP				9
#define	WDCTL_ADD_ROAM_MACLIST			10
#define	WDCTL_CLEAR_ROAM_MACLIST		11
#define	WDCTL_SHOW_ROAM_MACLIST			12
#define	WDCTL_ADD_UNTRUSTED_MACLIST		13
#define	WDCTL_CLEAR_UNTRUSTED_MACLIST	14
#define	WDCTL_SHOW_UNTRUSTED_MACLIST	15
#define	WDCTL_ADD_TRUSTED_MACLIST		16
#define	WDCTL_CLEAR_TRUSTED_MACLIST		17
#define	WDCTL_SHOW_TRUSTED_MACLIST		18
#define	WDCTL_USER_CFG_SAVE				19
#define	WDCTL_ADD_WILDCARD_DOMAIN		20
#define	WDCTL_ADD_TRUSTED_IPLIST		21
#define	WDCTL_ADD_ONLINE_CLIENT			22
#define WDCTL_DEL_TRUSTED_DOMAINS		23
#define	WDCTL_CLEAR_TRUSTED_IPLIST		24
#define	WDCTL_DEL_TRUSTED_IPLIST		25
#define WDCTL_DEL_TRUSTED_MACLIST		26
#define	WDCTL_DEL_UNTRUSTED_MACLIST		27
#define	WDCTL_ADD_TRUSTED_PAN_DOMAINS	28
#define	WDCTL_DEL_TRUSTED_PAN_DOMAINS	29
#define	WDCTL_CLEAR_TRUSTED_PAN_DOMAINS	30
#define	WDCTL_SHOW_TRUSTED_PAN_DOMAINS	31
#define	WDCTL_ADD_TRUSTED_LOCAL_MACLIST			32
#define	WDCTL_DEL_TRUSTED_LOCAL_MACLIST			33
#define	WDCTL_SHOW_TRUSTED_LOCAL_MACLIST		34
#define	WDCTL_CLEAR_TRUSTED_LOCAL_MACLIST		35

#endif
