name: compile apfree-wifidog in ubuntu system

on:
  workflow_dispatch:
    inputs:
      firewall:
        description: 'Firewall version (fw4 or fw3)'
        required: true
        default: 'fw4'
        type: choice
        options:
          - fw4
          - fw3

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2
    
    - name: install other depend lib
      run: |
          sudo apt-get update -y
          sudo apt-get install -y libjson-c-dev
          sudo apt-get install -y libevent-dev
          sudo apt-get install -y lua5.1 lua5.1-dev
          sudo apt-get install -y nftables
          sudo apt-get install -y libnetfilter-queue-dev
          sudo apt-get install -y libmosquitto-dev

    - name: install libubox
      run: |
        git clone https://github.com/git-openwrt-org-mirror/libubox.git
        cd libubox
        mkdir build && cd build && cmake ..
        sudo make install
        
    - name: install uci
      run: |
        git clone https://github.com/git-openwrt-org-mirror/uci.git
        cd uci
        mkdir build && cd build && cmake ..
        sudo make install

    - name: install iptables lib for apfree wifidog
      run: | 
        git clone https://github.com/liudf0716/iptables-apfree-wifidog.git
        cd iptables-apfree-wifidog
        ./autogen.sh
        ./configure --disable-nftables
        make
        sudo make install
    
    - name: compile apfree-wifidog
      run: |
        mkdir -p build
        cd build
        if [ "${{ github.event.inputs.firewall }}" = "fw3" ]; then
          cmake -DAW_FW3=ON ..
        else
          cmake ..
        fi
        make
        ldd src/wifidogx
        ldd src/wdctlx
